# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FicFeed' do

pod 'MWFeedParser'
pod 'Firebase'
pod 'Firebase/Messaging'
pod 'Firebase/Database'

end

target 'FicFeedTests' do

end

target 'FicFeedUITests' do

end

